import * as vg from '@uwdata/vgplot';

// configure the coordinator to use DuckDB-WASM
// creates a new database instance running in-browser
const wasm = await vg.wasmConnector({ log: true });
vg.coordinator().databaseConnector(wasm);

// load data into the database
// executes a query generated by the loadCSV helper
vg.coordinator().exec(vg.loadCSV('stocks', 'http://localhost:5173/data/stock-data.csv'));

// export const point = vg.Param.value(new Date('2013-05-13'));

// create an area chart, returned as an HTML element
// you can subsequently add this to your webpage
export default vg.plot(
	vg.style({ backgroundColor: 'transparent' }),
	vg.dot(vg.from('stocks'), {
		x: vg.sql`(Close - Open) / Open`,
		y: 'Volume',
		r: 'Volume',
		strokeOpacity: 0.2
	}),
	vg.axisX({
		color: 'white',
		label: 'Daily change (%)',
		percent: true
	}),
	vg.axisY({
		color: 'white',
		label: 'Daily trading volume'
	}),
	vg.yScale('log'),
	vg.xTickFormat('+f')
);
